// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeSsIIq2NrAn2nw_C1HbPlRljdjvvGv0s',
    appId: '1:667727691442:web:d5a6112732b95f826553ab',
    messagingSenderId: '667727691442',
    projectId: 'expenseflutter-ccb20',
    authDomain: 'expenseflutter-ccb20.firebaseapp.com',
    databaseURL: 'https://expenseflutter-ccb20-default-rtdb.firebaseio.com',
    storageBucket: 'expenseflutter-ccb20.firebasestorage.app',
    measurementId: 'G-00HLDP4NKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1cadi1of8TiIiVr3rr91VmgjmVvPmpG0',
    appId: '1:667727691442:android:b92641db4889e0296553ab',
    messagingSenderId: '667727691442',
    projectId: 'expenseflutter-ccb20',
    databaseURL: 'https://expenseflutter-ccb20-default-rtdb.firebaseio.com',
    storageBucket: 'expenseflutter-ccb20.firebasestorage.app',
  );
}
